tag: release
app: matrix
data: /data
repository: docker.com
domain: paramg.com
port: 80
protocol: http
database: paramg.database.windows.net
email: paramesh.gunasekaran@gmail.com

kong_data_port: 8000
kong_admin_port: 8001