- name: start nuget feed
  docker_container:
    name: nuget
    image: loicsharma/baget
    restart_policy: always
    recreate: yes
    env:
      ApiKey: "{{nuget_api_key}}"
      Storage__Type: FileSystem
      Storage__Path: /var/baget/packages
      Database__Type: Sqlite
      Database__ConnectionString: Data Source=/var/baget/baget.db
      Search__Type: Database
      Mirror__Enabled: true
      Mirror__PackageSource: "https://api.nuget.org/v3/index.json"
      AllowPackageOverwrites: true
      PackageDeletionBehavior: "Unlist"
    volumes:
      - "{{data}}/{{app}}/{{env}}/nuget:/var/baget"
    ports:
      - "0.0.0.0:8888:80"
    networks:
      - name: "platform.build"