tag: ci
app: matrix
data: /data
docker_repository: docker.com
domain: paramg.com
port: 8090
protocol: http
database: paramg.database.windows.net
email: paramesh.gunasekaran@gmail.com

kong_data_port: 9900
kong_admin_port: 9901